import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import MyContextProvider from "./_context/UpdateCartItems";
import Header from "./_components/Header/Header";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Grocery Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={poppins.className}>
          <MyContextProvider>
            <Header />
            {children}
            <Toaster className="text-xl" />
          </MyContextProvider>
        </body>
      </html>
    </>
  );
}
